Coc
gdgcloudkol/ccd2022 pull request #15
Opened 2022-06-29 19:56 UTC by mdsams

2022-06-29 21:55 UTC, cosmo3769 commented
@mdsams Hey, it looks good. Some changes to be done: 

* The content is not responsive in other screen(From Anti Harassment Policy, it is slightly right shifted.)
* The image is not responsive too. It is taking full width of the screen when inspecting. 
* The image box shadow is perfect in desktop, but when inspecting the box shadow is overlapping with faq section.

2022-06-29 21:56 UTC, cosmo3769 requested changes
@mdsams Hey, it looks good. Some changes to be done:

The content is not responsive in other screen(From Anti Harassment Policy, it is slightly right shifted.)
The image is not responsive too. It is taking full width of the screen when inspecting.
The image box shadow is perfect in desktop, but when inspecting the box shadow is overlapping with faq section.

2022-06-29 21:59 UTC, cosmo3769 requested changes

2022-06-29 21:59 UTC, cosmo3769 commented on src/Components/Coc/Coc.tsx
> +            Why do we have an official Anti-Harassment policy for Developer Student
Have to change from Developer Student Clubs NSEC to Google Developer Group.

2022-06-30 10:47 UTC, cosmo3769 approved these changes
LGTM.

2022-07-06 09:53 UTC, avinashkranjan approved these changes
LGTM..

2022-07-06 09:53 UTC, merged